# ─────────────────────────────────────────
# FutureKawa — Simulateur IoT
# ─────────────────────────────────────────
simulator.subscriber.enabled=false
# ─── MQTT Broker ───
mqtt.broker.url=tcp://localhost:1883
mqtt.broker.clientId=futurekawa-iot-simulator
server.port=3099

# ─── Fréquence d'envoi (ms) ───
# 10000 = toutes les 10 secondes
simulator.interval=10000

# ─── Activer les anomalies simulées ───
# Une anomalie sera générée toutes les ~5 mesures
simulator.anomaly.enabled=true
simulator.anomaly.frequency=5