# ─────────────────────────────────────────
# FutureKawa — Backend central
# ─────────────────────────────────────────

server.port=3000

# ─── PostgreSQL CENTRAL ───
spring.datasource.url=jdbc:postgresql://localhost:5432/futurekawa_central
spring.datasource.username=postgres
spring.datasource.password=postgres1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ─── JPA ───
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ─── URLs des backends pays ───
country.brazil.url=http://localhost:3001
country.colombia.url=http://localhost:3002
country.ecuador.url=http://localhost:3003


# ─── Timeout appels HTTP vers les pays (ms) ───
country.http.connect-timeout=3000
country.http.read-timeout=5000